
SQL> CREATE TABLE Products (
  2      ProductID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  3      ProductName VARCHAR2(100),
  4      Category VARCHAR2(50),
  5      Price NUMBER(10,2),
  6      StockQuantity INT
  7  );

Table created.

SQL> CREATE TABLE Sales (
  2      SaleID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  3      SaleDate DATE,
  4      TotalAmount NUMBER(10,2)
  5  );

Table created.

SQL> CREATE TABLE SaleDetails (
  2      DetailID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  3      SaleID NUMBER REFERENCES Sales(SaleID),
  4      ProductID NUMBER REFERENCES Products(ProductID),
  5      Quantity INT,
  6      UnitPrice NUMBER(10,2)
  7  );

Table created.

SQL> INSERT INTO Products (ProductName, Category, Price, StockQuantity) VALUES ('Milk', 'Dairy', 1.50, 120);

1 row created.

SQL> INSERT INTO Products (ProductName, Category, Price, StockQuantity) VALUES ('Cheese', 'Dairy', 3.00, 45);

1 row created.

SQL> INSERT INTO Products (ProductName, Category, Price, StockQuantity) VALUES ('Juice', 'Beverages', 2.00, 150);

1 row created.

SQL> INSERT INTO Products (ProductName, Category, Price, StockQuantity) VALUES ('Soda', 'Beverages', 1.20, 200);

1 row created.

SQL> INSERT INTO Products (ProductName, Category, Price, StockQuantity) VALUES ('Bread', 'Bakery', 1.00, 30);

1 row created.

SQL> INSERT INTO Sales (SaleDate, TotalAmount) VALUES (TO_DATE('2026-06-25', 'YYYY-MM-DD'), 7.00);

1 row created.

SQL> INSERT INTO Sales (SaleDate, TotalAmount) VALUES (TO_DATE('2026-06-26', 'YYYY-MM-DD'), 12.50);

1 row created.

SQL> INSERT INTO Sales (SaleDate, TotalAmount) VALUES (TO_DATE('2026-06-27', 'YYYY-MM-DD'), 4.50);

1 row created.

SQL> INSERT INTO SaleDetails (SaleID, ProductID, Quantity, UnitPrice) VALUES (1, 1, 2, 1.50);

1 row created.

SQL> INSERT INTO SaleDetails (SaleID, ProductID, Quantity, UnitPrice) VALUES (1, 3, 2, 2.00);

1 row created.

SQL> INSERT INTO SaleDetails (SaleID, ProductID, Quantity, UnitPrice) VALUES (2, 2, 3, 3.00);

1 row created.

SQL> INSERT INTO SaleDetails (SaleID, ProductID, Quantity, UnitPrice) VALUES (2, 5, 3, 1.00);

1 row created.

SQL> INSERT INTO SaleDetails (SaleID, ProductID, Quantity, UnitPrice) VALUES (3, 1, 3, 1.50);

1 row created.

SQL> COMMIT;

Commit complete.

SQL> WITH CriticalStock AS (
  2      SELECT ProductID, ProductName, Category, StockQuantity, (StockQuantity * Price) AS StockValue
  3      FROM Products
  4      WHERE StockQuantity < 50
  5  )
  6  SELECT Category, SUM(StockValue) AS TotalCriticalValue, COUNT(ProductID) AS LowStockItemsCount
  7  FROM CriticalStock
  8  GROUP BY Category;

CATEGORY                                           TOTALCRITICALVALUE
-------------------------------------------------- ------------------
LOWSTOCKITEMSCOUNT
------------------
Dairy                                                            135
                 1

Bakery                                                            30
                 1

SQL> SELECT ProductName,Category,Price,
  2  ROW_NUMBER()OVER(ORDER BY Price DESC)As RN
  3  FROM Products;

PRODUCTNAME                                                         CATEGORY                                                 PRICE         RN
---------------------------------------------------------------------------------------------------- -------------------------------------------------- ---------- ----------
Cheese                                                              Dairy                                                       3           1
Juice                                                               Beverages                                                   2           2
Milk                                                                Dairy                                                      1.5          3
Soda                                                                Beverages                                                  1.2          4
Bread                                                               Bakery                                                      1           5

SQL> ed
Wrote file afiedt.buf

  1  SELECT ProductName,Category,Price,
  2  ROW_NUMBER()OVER(ORDER BY Price DESC)As RN
  3* FROM Products
SQL> ed
Wrote file afiedt.buf

  1  SELECT ProductName,Category,Price,
  2  ROW_NUMBER()OVER(ORDER BY Price DESC)As RN
  3* FROM Products
SQL> /

PRODUCTNAME                                                         CATEGORY                                                 PRICE         RN
---------------------------------------------------------------------------------------------------- -------------------------------------------------- ---------- ----------
Cheese                                                              Dairy                                                       3           1
Juice                                                               Beverages                                                   2           2
Milk                                                                Dairy                                                      1.5          3
Soda                                                                Beverages                                                  1.2          4
Bread                                                               Bakery                                                      1           5
